"""frida-gadget version information."""
__title__ = "frida-gadget"
__version__ = "1.3.9"
__description__ = "Automated Frida Gadget injection tool"
__url__ = "https://github.com/ksg97031/frida-gadget"
__author__ = "ksg97031"
__author_email__ = "ksg97031@gmail.com"
